In [63]:
import pandas as pd

In [64]:
df = pd.read_csv("vv_data_20250722.csv")

# check null info

In [65]:
df.isna().sum()

Unnamed: 0               0
uid                      0
price                    0
suv_prob                 0
vert_prob                0
sedan_prob               0
coupe_prob               0
hatchback_prob           0
window_damage_prob       0
door_damage_prob         0
bumper_damage_prob       0
hood_damage_prob         0
excellent_cond_prob      0
average_cond_prob        0
year                   135
make                   140
model_name             156
trim                   650
mileage                285
title_status           158
transmission           407
engine_cylinders       566
displacement           762
dtype: int64

In [66]:
na_sums = df.isna().sum()
na_sums /= df.shape[0]
na_sums = na_sums[na_sums < 0.5] # filter to columns with <50% missing
dropped = set(na_sums.index) ^ set(df.columns) # set of columns that got dropped

In [67]:
df = df[na_sums.index]
df

,Unnamed: 0,uid,price,suv_prob,vert_prob,sedan_prob,coupe_prob,hatchback_prob,window_damage_prob,door_damage_prob,bumper_damage_prob,hood_damage_prob,excellent_cond_prob,average_cond_prob,year,make,model_name,mileage,title_status,transmission
0,0,7865789467,1800.0,0.475830,0.511719,0.736328,0.074585,0.422119,0.457275,0.240845,0.137329,0.332031,0.669434,0.200439,2003,Honda,Accord EX,NaN,NaN,Automatic
1,1,7865784701,2800.0,0.186523,0.113647,0.741211,0.034515,0.250977,0.120483,0.157104,0.050415,0.509277,0.583984,0.128296,2003,Honda,Accord,NaN,NaN,NaN
2,2,7865780123,1999.0,0.412354,0.242432,0.717773,0.027008,0.605957,0.320801,0.520508,0.157471,0.259766,0.703125,0.392090,2000,Accord,Lx,159000,NaN,Needs repair/replace (current one is going out)
3,3,7865763347,6995.0,0.137573,0.114441,0.713379,0.083740,0.314941,0.418457,0.186279,0.111694,0.746582,0.289795,0.188599,2010,Honda,Accord LX Sedan 4-DOORS,105000,clean,Automatic
4,4,7865716774,22000.0,0.622070,0.347656,0.853516,0.156128,0.516113,0.452393,0.161377,0.466064,0.605957,0.635742,0.570801,18,Accord,Sport,81100,clean,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1039,1039,7864876044,4950.0,0.572754,0.162476,0.880859,0.042725,0.556152,0.214478,0.337158,0.123596,0.466797,0.749023,0.346680,2010,Volvo,V50 Wagon,140000,California Clean Title,Automatic
1040,1040,7864874222,3950.0,0.875488,0.158569,0.430908,0.029251,0.509277,0.339355,0.288574,0.263916,0.324219,0.566406,0.402832,2001,Subaru,Forester,137000,California Clean Title,Automatic
1041,1041,7864873613,4250.0,0.979492,0.600586,0.625977,0.050934,0.406006,0.411133,0.234253,0.586914,0.411377,0.686523,0.337646,2005,Toyota,Tundra SR5 Double Cab,290000,California Clean Title,Automatic
1042,1042,7864872236,3500.0,0.400879,0.884277,0.750488,0.117065,0.224854,0.210449,0.149414,0.395752,0.627930,0.739746,0.380371,2001,Toyota,Camry Solara,190000,California Clean Title,Automatic
1043,1043,7863467682,3450.0,0.565918,0.107971,0.926270,0.394775,0.387451,0.360840,0.285400,0.022552,0.297363,0.742188,0.176392,2008,Audi,A4,165000,Clean California title,Automatic

In [68]:
df.columns

Index(['Unnamed: 0', 'uid', 'price', 'suv_prob', 'vert_prob', 'sedan_prob',
       'coupe_prob', 'hatchback_prob', 'window_damage_prob',
       'door_damage_prob', 'bumper_damage_prob', 'hood_damage_prob',
       'excellent_cond_prob', 'average_cond_prob', 'year', 'make',
       'model_name', 'mileage', 'title_status', 'transmission'],
      dtype='object')

# Cleaning

In [69]:
import warnings

## Price

In [70]:
def to_plausible_price(x):
    try:
        x = float(x)
    except:
        warnings.warn(f"cant turn this value to numeric: {x}")
        return -1
        
    if x <= 1000 or x >= 999999:
        return -1
    else:
        return x

In [71]:
num_price = df['price'].dropna().apply(lambda x: to_plausible_price(x))
num_price = num_price[num_price > -1]
print(f"$: min: {num_price.min()} , avg: {num_price.mean()}, max: {num_price.max()}")
min_price, max_price = num_price.min(), num_price.max()

$: min: 1100.0 , avg: 7211.562248995984, max: 92000.0

## Year

In [72]:
import warnings
def to_plausible_year(x):
    try:
        x = int(x)
    except:
        warnings.warn(f"cant turn this value to numeric: {x}")
        return -1
        
    if x <= 1900 or x >= 2025:
        return -1
    else:
        return x

In [73]:
num_year = df['year'].dropna().apply(lambda x: to_plausible_year(x))
num_year = num_year[num_year > -1]
print(f"year: min: {num_year.min()} , mode: {num_year.mode().squeeze()}, max: {num_year.max()}")
min_year, max_year = num_year.min(), num_year.max()

year: min: 1936 , mode: 2007, max: 2024

C:\Users\Kyle\AppData\Local\Temp\ipykernel_10488\2600713686.py:6: UserWarning: cant turn this value to numeric: Unknown
  warnings.warn(f"cant turn this value to numeric: {x}")
C:\Users\Kyle\AppData\Local\Temp\ipykernel_10488\2600713686.py:6: UserWarning: cant turn this value to numeric: Not available
  warnings.warn(f"cant turn this value to numeric: {x}")
C:\Users\Kyle\AppData\Local\Temp\ipykernel_10488\2600713686.py:6: UserWarning: cant turn this value to numeric: not available
  warnings.warn(f"cant turn this value to numeric: {x}")
C:\Users\Kyle\AppData\Local\Temp\ipykernel_10488\2600713686.py:6: UserWarning: cant turn this value to numeric: Not Available
  warnings.warn(f"cant turn this value to numeric: {x}")
C:\Users\Kyle\AppData\Local\Temp\ipykernel_10488\2600713686.py:6: UserWarning: cant turn this value to numeric: many
  warnings.warn(f"cant turn this value to numeric: {x}")
C:\Users\Kyle\AppData\Local\Temp\ipykernel_10488\2600713686.py:6: UserWarning: cant turn this value to numeric: ['99-02', '03-05', '96-99', '00-05', '99-01', '02-07']
  warnings.warn(f"cant turn this value to numeric: {x}")
C:\Users\Kyle\AppData\Local\Temp\ipykernel_10488\2600713686.py:6: UserWarning: cant turn this value to numeric: 99-02
  warnings.warn(f"cant turn this value to numeric: {x}")
C:\Users\Kyle\AppData\Local\Temp\ipykernel_10488\2600713686.py:6: UserWarning: cant turn this value to numeric: empty
  warnings.warn(f"cant turn this value to numeric: {x}")
C:\Users\Kyle\AppData\Local\Temp\ipykernel_10488\2600713686.py:6: UserWarning: cant turn this value to numeric: unknown
  warnings.warn(f"cant turn this value to numeric: {x}")
C:\Users\Kyle\AppData\Local\Temp\ipykernel_10488\2600713686.py:6: UserWarning: cant turn this value to numeric: New (Year not specified)
  warnings.warn(f"cant turn this value to numeric: {x}")
C:\Users\Kyle\AppData\Local\Temp\ipykernel_10488\2600713686.py:6: UserWarning: cant turn this value to numeric: Loaded
  warnings.warn(f"cant turn this value to numeric: {x}")
C:\Users\Kyle\AppData\Local\Temp\ipykernel_10488\2600713686.py:6: UserWarning: cant turn this value to numeric: available
  warnings.warn(f"cant turn this value to numeric: {x}")
C:\Users\Kyle\AppData\Local\Temp\ipykernel_10488\2600713686.py:6: UserWarning: cant turn this value to numeric: unavailable
  warnings.warn(f"cant turn this value to numeric: {x}")
C:\Users\Kyle\AppData\Local\Temp\ipykernel_10488\2600713686.py:6: UserWarning: cant turn this value to numeric: last year
  warnings.warn(f"cant turn this value to numeric: {x}")
C:\Users\Kyle\AppData\Local\Temp\ipykernel_10488\2600713686.py:6: UserWarning: cant turn this value to numeric: Honda
  warnings.warn(f"cant turn this value to numeric: {x}")
C:\Users\Kyle\AppData\Local\Temp\ipykernel_10488\2600713686.py:6: UserWarning: cant turn this value to numeric: 200K range
  warnings.warn(f"cant turn this value to numeric: {x}")
C:\Users\Kyle\AppData\Local\Temp\ipykernel_10488\2600713686.py:6: UserWarning: cant turn this value to numeric: 150K (year not specified)
  warnings.warn(f"cant turn this value to numeric: {x}")
C:\Users\Kyle\AppData\Local\Temp\ipykernel_10488\2600713686.py:6: UserWarning: cant turn this value to numeric: Not specified
  warnings.warn(f"cant turn this value to numeric: {x}")
C:\Users\Kyle\AppData\Local\Temp\ipykernel_10488\2600713686.py:6: UserWarning: cant turn this value to numeric: ['2018', '2018']
  warnings.warn(f"cant turn this value to numeric: {x}")
C:\Users\Kyle\AppData\Local\Temp\ipykernel_10488\2600713686.py:6: UserWarning: cant turn this value to numeric: NOT AVAILABLE
  warnings.warn(f"cant turn this value to numeric: {x}")
C:\Users\Kyle\AppData\Local\Temp\ipykernel_10488\2600713686.py:6: UserWarning: cant turn this value to numeric: 5sp
  warnings.warn(f"cant turn this value to numeric: {x}")
C:\Users\Kyle\AppData\Local\Temp\ipykernel_10488\2600713686.py:6: UserWarning: cant turn this value to numeric: ['2010', '2010', '2005']
  warnings.warn(f"cant turn this value to numeric: {x}")
C:\Users\Kyle\AppData\Local\Temp\ipykernel_10488\2600713686.py:6: UserWarning: cant turn this value to numeric: 3.5
  warnings.warn(f"cant turn this value to numeric: {x}")
C:\Users\Kyle\AppData\Local\Temp\ipykernel_10488\2600713686.py:6: UserWarning: cant turn this value to numeric: 303hp engine
  warnings.warn(f"cant turn this value to numeric: {x}")
C:\Users\Kyle\AppData\Local\Temp\ipykernel_10488\2600713686.py:6: UserWarning: cant turn this value to numeric: old generation model
  warnings.warn(f"cant turn this value to numeric: {x}")

## Make

In [74]:
common_makes = df['make'].value_counts()[df['make'].value_counts() > 10]

In [75]:
common_makes # VW = Volkswagen

make
Toyota        216
Honda         205
Ford           99
Nissan         63
Mazda          32
Volvo          22
Chevy          22
VW             17
Lexus          15
Volkswagen     13
Chevrolet      12
Name: count, dtype: int64

## Model

In [76]:
common_models = df['model_name'].value_counts()[df['model_name'].value_counts() > 10]
common_models # code everything else as "not available"

model_name
Camry            37
Accord           36
Corolla          31
Civic            30
Altima           28
Explorer         27
Focus            23
3                14
Jetta            14
CR-V             13
Corolla LE       13
not available    12
Name: count, dtype: int64

## Mileage

In [77]:
import re
def to_plausible_mileage(x):
    k_pattern = r'\b(\d+(?:\.\d+)?)[kK]\b'
    if isinstance(x, str):
        if found_k := re.findall(k_pattern, x):
            found_k = found_k[0]
            converted = int(float(found_k.rstrip('kK'))*1000)
            print(f"Converting {found_k}k -> {converted}")
            return converted

    try:
        x = float(x)
    except:
        warnings.warn(f"cant turn this value to numeric: {x}")
        return -1
        
    if x <= 0 or x >= 400000:
        return -1
    else:
        return x

In [78]:
num_mileage = df['mileage'].dropna().apply(lambda x: to_plausible_mileage(x))
num_mileage = num_mileage[num_mileage > -1]
print(f"mileage: min: {num_mileage.min()} , mode: {num_mileage.mode().squeeze()}, max: {num_mileage.max()}")
min_mileage, max_mileage = num_mileage.min(), num_mileage.max()

Converting 140k -> 140000
Converting 200k -> 200000
Converting 140k -> 140000
Converting 165k -> 165000
Converting 125k -> 125000
Converting 89k -> 89000
Converting 120k -> 120000
Converting 201k -> 201000
Converting 144k -> 144000
Converting 125k -> 125000
Converting 149k -> 149000
Converting 149k -> 149000
mileage: min: 9.0 , mode: 155000.0, max: 373000.0

C:\Users\Kyle\AppData\Local\Temp\ipykernel_10488\3161316120.py:14: UserWarning: cant turn this value to numeric: []
  warnings.warn(f"cant turn this value to numeric: {x}")
C:\Users\Kyle\AppData\Local\Temp\ipykernel_10488\3161316120.py:14: UserWarning: cant turn this value to numeric: not available
  warnings.warn(f"cant turn this value to numeric: {x}")
C:\Users\Kyle\AppData\Local\Temp\ipykernel_10488\3161316120.py:14: UserWarning: cant turn this value to numeric: low mileage
  warnings.warn(f"cant turn this value to numeric: {x}")
C:\Users\Kyle\AppData\Local\Temp\ipykernel_10488\3161316120.py:14: UserWarning: cant turn this value to numeric: Not available
  warnings.warn(f"cant turn this value to numeric: {x}")
C:\Users\Kyle\AppData\Local\Temp\ipykernel_10488\3161316120.py:14: UserWarning: cant turn this value to numeric: Few miles
  warnings.warn(f"cant turn this value to numeric: {x}")
C:\Users\Kyle\AppData\Local\Temp\ipykernel_10488\3161316120.py:14: UserWarning: cant turn this value to numeric: [131717, 55600]
  warnings.warn(f"cant turn this value to numeric: {x}")
C:\Users\Kyle\AppData\Local\Temp\ipykernel_10488\3161316120.py:14: UserWarning: cant turn this value to numeric: low miles
  warnings.warn(f"cant turn this value to numeric: {x}")
C:\Users\Kyle\AppData\Local\Temp\ipykernel_10488\3161316120.py:14: UserWarning: cant turn this value to numeric: [300000, 150000, 330000]
  warnings.warn(f"cant turn this value to numeric: {x}")
C:\Users\Kyle\AppData\Local\Temp\ipykernel_10488\3161316120.py:14: UserWarning: cant turn this value to numeric: 10+K miles
  warnings.warn(f"cant turn this value to numeric: {x}")
C:\Users\Kyle\AppData\Local\Temp\ipykernel_10488\3161316120.py:14: UserWarning: cant turn this value to numeric: 158HP (implied, not actual mileage)
  warnings.warn(f"cant turn this value to numeric: {x}")
C:\Users\Kyle\AppData\Local\Temp\ipykernel_10488\3161316120.py:14: UserWarning: cant turn this value to numeric: Low Miles
  warnings.warn(f"cant turn this value to numeric: {x}")

In [79]:
def clean_bool(x):
    if not isinstance(x, str):
        return False
    if "clean" in x:
        return True
    return False

df['title_status'].apply(lambda x: clean_bool(x)).value_counts()

title_status
False    592
True     452
Name: count, dtype: int64

## transmission

In [80]:
def sort_transmission_type(x):
    if not isinstance(x, str):
        return "Unknown"
    if "automatic" in x.lower() or "cvt" in x.lower():
        return "Automatic"
    if "manual" in x.lower():
        return "Manual"
    if "smg" in x.lower() or "sequential" in x.lower():
        return "Sequential"
    return "Unknown"
df['transmission'].apply(lambda x: sort_transmission_type(x)).value_counts()

transmission
Automatic     485
Unknown       450
Manual        108
Sequential      1
Name: count, dtype: int64

# Quick Clean up

In [81]:
# cleaning
df['price'] = df['price'].apply(lambda x: to_plausible_price(x))
df['year'] = df['year'].apply(lambda x: to_plausible_year(x))
df['make'] = df['make'].replace("VW", "Volkswagen")
df['mileage'] = df['mileage'].apply(lambda x: to_plausible_mileage(x))
df['title_status'] = df['title_status'].apply(lambda x: clean_bool(x))
df['transmission'] = df['transmission'].apply(lambda x: sort_transmission_type(x))

# filtering
df = df[(df['price']>= min_price) & (df['price'] <= max_price)]
df = df[(df['year'] >= min_year) & (df['year'] <= max_year)]
df = df[(df['mileage'] >= min_mileage) & (df['mileage'] <= max_mileage)]
df = df.drop(columns=["Unnamed: 0"])
# these are too strict - maybe let autogluon encode them
# df = df[df['make'].isin(common_makes.index)]
# df = df[df['model_name'].isin(common_models.index)]

Converting 140k -> 140000
Converting 200k -> 200000
Converting 140k -> 140000
Converting 165k -> 165000
Converting 125k -> 125000
Converting 89k -> 89000
Converting 120k -> 120000
Converting 201k -> 201000
Converting 144k -> 144000
Converting 125k -> 125000
Converting 149k -> 149000
Converting 149k -> 149000

C:\Users\Kyle\AppData\Local\Temp\ipykernel_10488\2600713686.py:6: UserWarning: cant turn this value to numeric: nan
  warnings.warn(f"cant turn this value to numeric: {x}")
C:\Users\Kyle\AppData\Local\Temp\ipykernel_10488\2600713686.py:6: UserWarning: cant turn this value to numeric: Unknown
  warnings.warn(f"cant turn this value to numeric: {x}")
C:\Users\Kyle\AppData\Local\Temp\ipykernel_10488\2600713686.py:6: UserWarning: cant turn this value to numeric: Not available
  warnings.warn(f"cant turn this value to numeric: {x}")
C:\Users\Kyle\AppData\Local\Temp\ipykernel_10488\2600713686.py:6: UserWarning: cant turn this value to numeric: not available
  warnings.warn(f"cant turn this value to numeric: {x}")
C:\Users\Kyle\AppData\Local\Temp\ipykernel_10488\2600713686.py:6: UserWarning: cant turn this value to numeric: Not Available
  warnings.warn(f"cant turn this value to numeric: {x}")
C:\Users\Kyle\AppData\Local\Temp\ipykernel_10488\2600713686.py:6: UserWarning: cant turn this value to numeric: many
  warnings.warn(f"cant turn this value to numeric: {x}")
C:\Users\Kyle\AppData\Local\Temp\ipykernel_10488\2600713686.py:6: UserWarning: cant turn this value to numeric: ['99-02', '03-05', '96-99', '00-05', '99-01', '02-07']
  warnings.warn(f"cant turn this value to numeric: {x}")
C:\Users\Kyle\AppData\Local\Temp\ipykernel_10488\2600713686.py:6: UserWarning: cant turn this value to numeric: 99-02
  warnings.warn(f"cant turn this value to numeric: {x}")
C:\Users\Kyle\AppData\Local\Temp\ipykernel_10488\2600713686.py:6: UserWarning: cant turn this value to numeric: empty
  warnings.warn(f"cant turn this value to numeric: {x}")
C:\Users\Kyle\AppData\Local\Temp\ipykernel_10488\2600713686.py:6: UserWarning: cant turn this value to numeric: unknown
  warnings.warn(f"cant turn this value to numeric: {x}")
C:\Users\Kyle\AppData\Local\Temp\ipykernel_10488\2600713686.py:6: UserWarning: cant turn this value to numeric: New (Year not specified)
  warnings.warn(f"cant turn this value to numeric: {x}")
C:\Users\Kyle\AppData\Local\Temp\ipykernel_10488\2600713686.py:6: UserWarning: cant turn this value to numeric: Loaded
  warnings.warn(f"cant turn this value to numeric: {x}")
C:\Users\Kyle\AppData\Local\Temp\ipykernel_10488\2600713686.py:6: UserWarning: cant turn this value to numeric: available
  warnings.warn(f"cant turn this value to numeric: {x}")
C:\Users\Kyle\AppData\Local\Temp\ipykernel_10488\2600713686.py:6: UserWarning: cant turn this value to numeric: unavailable
  warnings.warn(f"cant turn this value to numeric: {x}")
C:\Users\Kyle\AppData\Local\Temp\ipykernel_10488\2600713686.py:6: UserWarning: cant turn this value to numeric: last year
  warnings.warn(f"cant turn this value to numeric: {x}")
C:\Users\Kyle\AppData\Local\Temp\ipykernel_10488\2600713686.py:6: UserWarning: cant turn this value to numeric: Honda
  warnings.warn(f"cant turn this value to numeric: {x}")
C:\Users\Kyle\AppData\Local\Temp\ipykernel_10488\2600713686.py:6: UserWarning: cant turn this value to numeric: 200K range
  warnings.warn(f"cant turn this value to numeric: {x}")
C:\Users\Kyle\AppData\Local\Temp\ipykernel_10488\2600713686.py:6: UserWarning: cant turn this value to numeric: 150K (year not specified)
  warnings.warn(f"cant turn this value to numeric: {x}")
C:\Users\Kyle\AppData\Local\Temp\ipykernel_10488\2600713686.py:6: UserWarning: cant turn this value to numeric: Not specified
  warnings.warn(f"cant turn this value to numeric: {x}")
C:\Users\Kyle\AppData\Local\Temp\ipykernel_10488\2600713686.py:6: UserWarning: cant turn this value to numeric: ['2018', '2018']
  warnings.warn(f"cant turn this value to numeric: {x}")
C:\Users\Kyle\AppData\Local\Temp\ipykernel_10488\2600713686.py:6: UserWarning: cant turn this value to numeric: NOT AVAILABLE
  warnings.warn(f"cant turn this value to numeric: {x}")
C:\Users\Kyle\AppData\Local\Temp\ipykernel_10488\2600713686.py:6: UserWarning: cant turn this value to numeric: 5sp
  warnings.warn(f"cant turn this value to numeric: {x}")
C:\Users\Kyle\AppData\Local\Temp\ipykernel_10488\2600713686.py:6: UserWarning: cant turn this value to numeric: ['2010', '2010', '2005']
  warnings.warn(f"cant turn this value to numeric: {x}")
C:\Users\Kyle\AppData\Local\Temp\ipykernel_10488\2600713686.py:6: UserWarning: cant turn this value to numeric: 3.5
  warnings.warn(f"cant turn this value to numeric: {x}")
C:\Users\Kyle\AppData\Local\Temp\ipykernel_10488\2600713686.py:6: UserWarning: cant turn this value to numeric: 303hp engine
  warnings.warn(f"cant turn this value to numeric: {x}")
C:\Users\Kyle\AppData\Local\Temp\ipykernel_10488\2600713686.py:6: UserWarning: cant turn this value to numeric: old generation model
  warnings.warn(f"cant turn this value to numeric: {x}")
C:\Users\Kyle\AppData\Local\Temp\ipykernel_10488\3161316120.py:14: UserWarning: cant turn this value to numeric: []
  warnings.warn(f"cant turn this value to numeric: {x}")
C:\Users\Kyle\AppData\Local\Temp\ipykernel_10488\3161316120.py:14: UserWarning: cant turn this value to numeric: not available
  warnings.warn(f"cant turn this value to numeric: {x}")
C:\Users\Kyle\AppData\Local\Temp\ipykernel_10488\3161316120.py:14: UserWarning: cant turn this value to numeric: low mileage
  warnings.warn(f"cant turn this value to numeric: {x}")
C:\Users\Kyle\AppData\Local\Temp\ipykernel_10488\3161316120.py:14: UserWarning: cant turn this value to numeric: Not available
  warnings.warn(f"cant turn this value to numeric: {x}")
C:\Users\Kyle\AppData\Local\Temp\ipykernel_10488\3161316120.py:14: UserWarning: cant turn this value to numeric: Few miles
  warnings.warn(f"cant turn this value to numeric: {x}")
C:\Users\Kyle\AppData\Local\Temp\ipykernel_10488\3161316120.py:14: UserWarning: cant turn this value to numeric: [131717, 55600]
  warnings.warn(f"cant turn this value to numeric: {x}")
C:\Users\Kyle\AppData\Local\Temp\ipykernel_10488\3161316120.py:14: UserWarning: cant turn this value to numeric: low miles
  warnings.warn(f"cant turn this value to numeric: {x}")
C:\Users\Kyle\AppData\Local\Temp\ipykernel_10488\3161316120.py:14: UserWarning: cant turn this value to numeric: [300000, 150000, 330000]
  warnings.warn(f"cant turn this value to numeric: {x}")
C:\Users\Kyle\AppData\Local\Temp\ipykernel_10488\3161316120.py:14: UserWarning: cant turn this value to numeric: 10+K miles
  warnings.warn(f"cant turn this value to numeric: {x}")
C:\Users\Kyle\AppData\Local\Temp\ipykernel_10488\3161316120.py:14: UserWarning: cant turn this value to numeric: 158HP (implied, not actual mileage)
  warnings.warn(f"cant turn this value to numeric: {x}")
C:\Users\Kyle\AppData\Local\Temp\ipykernel_10488\3161316120.py:14: UserWarning: cant turn this value to numeric: Low Miles
  warnings.warn(f"cant turn this value to numeric: {x}")

In [82]:
df

,uid,price,suv_prob,vert_prob,sedan_prob,coupe_prob,hatchback_prob,window_damage_prob,door_damage_prob,bumper_damage_prob,hood_damage_prob,excellent_cond_prob,average_cond_prob,year,make,model_name,mileage,title_status,transmission
2,7865780123,1999.0,0.412354,0.242432,0.717773,0.027008,0.605957,0.320801,0.520508,0.157471,0.259766,0.703125,0.392090,2000,Accord,Lx,159000.0,False,Unknown
3,7865763347,6995.0,0.137573,0.114441,0.713379,0.083740,0.314941,0.418457,0.186279,0.111694,0.746582,0.289795,0.188599,2010,Honda,Accord LX Sedan 4-DOORS,105000.0,True,Automatic
6,7865539056,7500.0,0.401123,0.490723,0.787598,0.096924,0.407959,0.348633,0.289062,0.083313,0.533203,0.730957,0.808594,2012,Honda,Accord EX-L V6 Sedan,157000.0,False,Automatic
7,7865479488,6000.0,0.600586,0.373047,0.854492,0.137817,0.429199,0.792480,0.065491,0.253906,0.103516,0.769043,0.672363,2007,Honda,Accord EX,193000.0,True,Manual
8,7865461018,17500.0,0.421387,0.131714,0.760254,0.292969,0.681152,0.308594,0.095276,0.433838,0.372070,0.628906,0.659180,2016,Honda,Accord,37000.0,True,Manual
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1039,7864876044,4950.0,0.572754,0.162476,0.880859,0.042725,0.556152,0.214478,0.337158,0.123596,0.466797,0.749023,0.346680,2010,Volvo,V50 Wagon,140000.0,False,Automatic
1040,7864874222,3950.0,0.875488,0.158569,0.430908,0.029251,0.509277,0.339355,0.288574,0.263916,0.324219,0.566406,0.402832,2001,Subaru,Forester,137000.0,False,Automatic
1041,7864873613,4250.0,0.979492,0.600586,0.625977,0.050934,0.406006,0.411133,0.234253,0.586914,0.411377,0.686523,0.337646,2005,Toyota,Tundra SR5 Double Cab,290000.0,False,Automatic
1042,7864872236,3500.0,0.400879,0.884277,0.750488,0.117065,0.224854,0.210449,0.149414,0.395752,0.627930,0.739746,0.380371,2001,Toyota,Camry Solara,190000.0,False,Automatic
1043,7863467682,3450.0,0.565918,0.107971,0.926270,0.394775,0.387451,0.360840,0.285400,0.022552,0.297363,0.742188,0.176392,2008,Audi,A4,165000.0,False,Automatic

In [85]:
df.dtypes

uid                      int64
price                  float64
suv_prob               float64
vert_prob              float64
sedan_prob             float64
coupe_prob             float64
hatchback_prob         float64
window_damage_prob     float64
door_damage_prob       float64
bumper_damage_prob     float64
hood_damage_prob       float64
excellent_cond_prob    float64
average_cond_prob      float64
year                     int64
make                    object
model_name              object
mileage                float64
title_status              bool
transmission            object
dtype: object

# Modeling with Autogluon

In [86]:
from autogluon.tabular import TabularDataset, TabularPredictor

f:\car-project\.ds\Lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

In [88]:
ag_df = TabularDataset(df)
ag_df = ag_df.drop(columns=["uid"])

## eval via R^2 (biased by number of features)

In [93]:
predictor = TabularPredictor(label="price", eval_metric="r2")

No path specified. Models will be saved in: "AutogluonModels\ag-20250725_011628"

In [94]:
predictor.fit(ag_df)

Verbosity: 2 (Standard Logging)
=================== System Info ===================
AutoGluon Version:  1.3.1
Python Version:     3.12.10
Operating System:   Windows
Platform Machine:   AMD64
Platform Version:   10.0.22631
CPU Count:          24
Memory Avail:       13.81 GB / 31.76 GB (43.5%)
Disk Space Avail:   274.53 GB / 807.37 GB (34.0%)
===================================================
No presets specified! To achieve strong results with AutoGluon, it is recommended to use the available presets. Defaulting to `'medium'`...
	Recommended Presets (For more details refer to https://auto.gluon.ai/stable/tutorials/tabular/tabular-essentials.html#presets):
	presets='experimental' : New in v1.2: Pre-trained foundation model + parallel fits. The absolute best accuracy without consideration for inference speed. Does not support GPU.
	presets='best'         : Maximize accuracy. Recommended for most users. Use in competitions and benchmarks.
	presets='high'         : Strong accuracy with fast inference speed.
	presets='good'         : Good accuracy with very fast inference speed.
	presets='medium'       : Fast training time, ideal for initial prototyping.
Beginning AutoGluon training ...
AutoGluon will save models to "f:\car-project\AutogluonModels\ag-20250725_011628"
Train Data Rows:    594
Train Data Columns: 17
Label Column:       price
AutoGluon infers your prediction problem is: 'regression' (because dtype of label-column == float and many unique label-values observed).
	Label info (max, min, mean, stddev): (54998.0, 1200.0, 6983.9596, 5907.48997)
	If 'regression' is not the correct problem_type, please manually specify the problem_type parameter during Predictor init (You may specify problem_type as one of: ['binary', 'multiclass', 'regression', 'quantile'])
Problem Type:       regression
Preprocessing data ...
Using Feature Generators to preprocess the data ...
Fitting AutoMLPipelineFeatureGenerator...
	Available Memory:                    14144.99 MB
	Train Data (Original)  Memory Usage: 0.16 MB (0.0% of available memory)
	Inferring data type of each feature based on column values. Set feature_metadata_in to manually specify special dtypes of the features.
	Stage 1 Generators:
		Fitting AsTypeFeatureGenerator...
			Note: Converting 1 features to boolean dtype as they only contain 2 unique values.
	Stage 2 Generators:
		Fitting FillNaFeatureGenerator...
	Stage 3 Generators:
		Fitting IdentityFeatureGenerator...
		Fitting CategoryFeatureGenerator...
			Fitting CategoryMemoryMinimizeFeatureGenerator...
	Stage 4 Generators:
		Fitting DropUniqueFeatureGenerator...
	Stage 5 Generators:
		Fitting DropDuplicatesFeatureGenerator...
	Types of features in original data (raw dtype, special dtypes):
		('bool', [])   :  1 | ['title_status']
		('float', [])  : 12 | ['suv_prob', 'vert_prob', 'sedan_prob', 'coupe_prob', 'hatchback_prob', ...]
		('int', [])    :  1 | ['year']
		('object', []) :  3 | ['make', 'model_name', 'transmission']
	Types of features in processed data (raw dtype, special dtypes):
		('category', [])  :  3 | ['make', 'model_name', 'transmission']
		('float', [])     : 12 | ['suv_prob', 'vert_prob', 'sedan_prob', 'coupe_prob', 'hatchback_prob', ...]
		('int', [])       :  1 | ['year']
		('int', ['bool']) :  1 | ['title_status']
	0.0s = Fit runtime
	17 features in original data used to generate 17 features in processed data.
	Train Data (Processed) Memory Usage: 0.06 MB (0.0% of available memory)
Data preprocessing and feature engineering runtime = 0.05s ...
AutoGluon will gauge predictive performance using evaluation metric: 'r2'
	To change this, specify the eval_metric parameter of Predictor()
Automatically generating train/validation split with holdout_frac=0.2, Train Rows: 475, Val Rows: 119
User-specified model hyperparameters to be fit:
{
	'NN_TORCH': [{}],
	'GBM': [{'extra_trees': True, 'ag_args': {'name_suffix': 'XT'}}, {}, {'learning_rate': 0.03, 'num_leaves': 128, 'feature_fraction': 0.9, 'min_data_in_leaf': 3, 'ag_args': {'name_suffix': 'Large', 'priority': 0, 'hyperparameter_tune_kwargs': None}}],
	'CAT': [{}],
	'XGB': [{}],
	'FASTAI': [{}],
	'RF': [{'criterion': 'gini', 'ag_args': {'name_suffix': 'Gini', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'entropy', 'ag_args': {'name_suffix': 'Entr', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'squared_error', 'ag_args': {'name_suffix': 'MSE', 'problem_types': ['regression', 'quantile']}}],
	'XT': [{'criterion': 'gini', 'ag_args': {'name_suffix': 'Gini', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'entropy', 'ag_args': {'name_suffix': 'Entr', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'squared_error', 'ag_args': {'name_suffix': 'MSE', 'problem_types': ['regression', 'quantile']}}],
	'KNN': [{'weights': 'uniform', 'ag_args': {'name_suffix': 'Unif'}}, {'weights': 'distance', 'ag_args': {'name_suffix': 'Dist'}}],
}
Fitting 11 L1 models, fit_strategy="sequential" ...
Fitting model: KNeighborsUnif ...
	0.2771	 = Validation score   (r2)
	0.0s	 = Training   runtime
	0.02s	 = Validation runtime
Fitting model: KNeighborsDist ...
	-0.0538	 = Validation score   (r2)
	0.0s	 = Training   runtime
	0.02s	 = Validation runtime
Fitting model: LightGBMXT ...
	0.627	 = Validation score   (r2)
	0.51s	 = Training   runtime
	0.01s	 = Validation runtime
Fitting model: LightGBM ...
	0.6185	 = Validation score   (r2)
	0.54s	 = Training   runtime
	0.0s	 = Validation runtime
Fitting model: RandomForestMSE ...
	0.7003	 = Validation score   (r2)
	0.33s	 = Training   runtime
	0.03s	 = Validation runtime
Fitting model: CatBoost ...
	0.7453	 = Validation score   (r2)
	14.77s	 = Training   runtime
	0.0s	 = Validation runtime
Fitting model: ExtraTreesMSE ...
	0.6788	 = Validation score   (r2)
	0.28s	 = Training   runtime
	0.03s	 = Validation runtime
Fitting model: NeuralNetFastAI ...
	0.6472	 = Validation score   (r2)
	0.33s	 = Training   runtime
	0.0s	 = Validation runtime
Fitting model: XGBoost ...
	0.465	 = Validation score   (r2)
	0.46s	 = Training   runtime
	0.01s	 = Validation runtime
Fitting model: NeuralNetTorch ...
	0.73	 = Validation score   (r2)
	5.15s	 = Training   runtime
	0.01s	 = Validation runtime
Fitting model: LightGBMLarge ...
	0.5219	 = Validation score   (r2)
	0.91s	 = Training   runtime
	0.01s	 = Validation runtime
Fitting model: WeightedEnsemble_L2 ...
	Ensemble Weights: {'CatBoost': 0.5, 'NeuralNetTorch': 0.429, 'RandomForestMSE': 0.071}
	0.7621	 = Validation score   (r2)
	0.08s	 = Training   runtime
	0.0s	 = Validation runtime
AutoGluon training complete, total runtime = 23.8s ... Best model: WeightedEnsemble_L2 | Estimated inference throughput: 3348.0 rows/s (119 batch size)
TabularPredictor saved. To load, use: predictor = TabularPredictor.load("f:\car-project\AutogluonModels\ag-20250725_011628")

## Eval via RMSE , also train longer with expensive model zoo

In [95]:
predictor2 = TabularPredictor(label="price", eval_metric="root_mean_squared_error")
predictor2.fit(ag_df,
    presets="best_quality",
    num_bag_folds=5, #5-fold CV
    )

No path specified. Models will be saved in: "AutogluonModels\ag-20250725_012410"
Verbosity: 2 (Standard Logging)
=================== System Info ===================
AutoGluon Version:  1.3.1
Python Version:     3.12.10
Operating System:   Windows
Platform Machine:   AMD64
Platform Version:   10.0.22631
CPU Count:          24
Memory Avail:       13.36 GB / 31.76 GB (42.0%)
Disk Space Avail:   274.51 GB / 807.37 GB (34.0%)
===================================================
Presets specified: ['best_quality']
Setting dynamic_stacking from 'auto' to True. Reason: Enable dynamic_stacking when use_bag_holdout is disabled. (use_bag_holdout=False)
Stack configuration (auto_stack=True): num_stack_levels=1, num_bag_folds=5, num_bag_sets=1
DyStack is enabled (dynamic_stacking=True). AutoGluon will try to determine whether the input data is affected by stacked overfitting and enable or disable stacking as a consequence.
	This is used to identify the optimal `num_stack_levels` value. Copies of AutoGluon will be fit on subsets of the data. Then holdout validation data is used to detect stacked overfitting.
	Running DyStack for up to 900s of the 3600s of remaining time (25%).
2025-07-24 21:24:10,732	INFO util.py:154 -- Missing packages: ['ipywidgets']. Run `pip install -U ipywidgets`, then restart the notebook server for rich notebook output.
	Running DyStack sub-fit in a ray process to avoid memory leakage. Enabling ray logging (enable_ray_logging=True). Specify `ds_args={'enable_ray_logging': False}` if you experience logging issues.
2025-07-24 21:24:14,643	INFO worker.py:1843 -- Started a local Ray instance. View the dashboard at http://127.0.0.1:8265
		Context path: "f:\car-project\AutogluonModels\ag-20250725_012410\ds_sub_fit\sub_fit_ho"
(_dystack pid=34984) Running DyStack sub-fit ...
(_dystack pid=34984) f:\car-project\.ds\Lib\site-packages\autogluon\common\utils\utils.py:97: UserWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html. The pkg_resources package is slated for removal as early as 2025-11-30. Refrain from using this package or pin to Setuptools<81.
(_dystack pid=34984)   import pkg_resources
(_dystack pid=34984) Beginning AutoGluon training ... Time limit = 892s
(_dystack pid=34984) AutoGluon will save models to "f:\car-project\AutogluonModels\ag-20250725_012410\ds_sub_fit\sub_fit_ho"
(_dystack pid=34984) Train Data Rows:    528
(_dystack pid=34984) Train Data Columns: 17
(_dystack pid=34984) Label Column:       price
(_dystack pid=34984) Problem Type:       regression
(_dystack pid=34984) Preprocessing data ...
(_dystack pid=34984) Using Feature Generators to preprocess the data ...
(_dystack pid=34984) Fitting AutoMLPipelineFeatureGenerator...
(_dystack pid=34984) 	Available Memory:                    12054.15 MB
(_dystack pid=34984) 	Train Data (Original)  Memory Usage: 0.14 MB (0.0% of available memory)
(_dystack pid=34984) 	Inferring data type of each feature based on column values. Set feature_metadata_in to manually specify special dtypes of the features.
(_dystack pid=34984) 	Stage 1 Generators:
(_dystack pid=34984) 		Fitting AsTypeFeatureGenerator...
(_dystack pid=34984) 			Note: Converting 1 features to boolean dtype as they only contain 2 unique values.
(_dystack pid=34984) 	Stage 2 Generators:
(_dystack pid=34984) 		Fitting FillNaFeatureGenerator...
(_dystack pid=34984) 	Stage 3 Generators:
(_dystack pid=34984) 		Fitting IdentityFeatureGenerator...
(_dystack pid=34984) 		Fitting CategoryFeatureGenerator...
(_dystack pid=34984) 			Fitting CategoryMemoryMinimizeFeatureGenerator...
(_dystack pid=34984) 	Stage 4 Generators:
(_dystack pid=34984) 		Fitting DropUniqueFeatureGenerator...
(_dystack pid=34984) 	Stage 5 Generators:
(_dystack pid=34984) 		Fitting DropDuplicatesFeatureGenerator...
(_dystack pid=34984) 	Types of features in original data (raw dtype, special dtypes):
(_dystack pid=34984) 		('bool', [])   :  1 | ['title_status']
(_dystack pid=34984) 		('float', [])  : 12 | ['suv_prob', 'vert_prob', 'sedan_prob', 'coupe_prob', 'hatchback_prob', ...]
(_dystack pid=34984) 		('int', [])    :  1 | ['year']
(_dystack pid=34984) 		('object', []) :  3 | ['make', 'model_name', 'transmission']
(_dystack pid=34984) 	Types of features in processed data (raw dtype, special dtypes):
(_dystack pid=34984) 		('category', [])  :  3 | ['make', 'model_name', 'transmission']
(_dystack pid=34984) 		('float', [])     : 12 | ['suv_prob', 'vert_prob', 'sedan_prob', 'coupe_prob', 'hatchback_prob', ...]
(_dystack pid=34984) 		('int', [])       :  1 | ['year']
(_dystack pid=34984) 		('int', ['bool']) :  1 | ['title_status']
(_dystack pid=34984) 	0.0s = Fit runtime
(_dystack pid=34984) 	17 features in original data used to generate 17 features in processed data.
(_dystack pid=34984) 	Train Data (Processed) Memory Usage: 0.06 MB (0.0% of available memory)
(_dystack pid=34984) Data preprocessing and feature engineering runtime = 0.04s ...
(_dystack pid=34984) AutoGluon will gauge predictive performance using evaluation metric: 'root_mean_squared_error'
(_dystack pid=34984) 	This metric's sign has been flipped to adhere to being higher_is_better. The metric score can be multiplied by -1 to get the metric value.
(_dystack pid=34984) 	To change this, specify the eval_metric parameter of Predictor()
(_dystack pid=34984) Large model count detected (112 configs) ... Only displaying the first 3 models of each family. To see all, set `verbosity=3`.
(_dystack pid=34984) User-specified model hyperparameters to be fit:
(_dystack pid=34984) {
(_dystack pid=34984) 	'NN_TORCH': [{}, {'activation': 'elu', 'dropout_prob': 0.10077639529843717, 'hidden_size': 108, 'learning_rate': 0.002735937344002146, 'num_layers': 4, 'use_batchnorm': True, 'weight_decay': 1.356433327634438e-12, 'ag_args': {'name_suffix': '_r79', 'priority': -2}}, {'activation': 'elu', 'dropout_prob': 0.11897478034205347, 'hidden_size': 213, 'learning_rate': 0.0010474382260641949, 'num_layers': 4, 'use_batchnorm': False, 'weight_decay': 5.594471067786272e-10, 'ag_args': {'name_suffix': '_r22', 'priority': -7}}],
(_dystack pid=34984) 	'GBM': [{'extra_trees': True, 'ag_args': {'name_suffix': 'XT'}}, {}, {'learning_rate': 0.03, 'num_leaves': 128, 'feature_fraction': 0.9, 'min_data_in_leaf': 3, 'ag_args': {'name_suffix': 'Large', 'priority': 0, 'hyperparameter_tune_kwargs': None}}],
(_dystack pid=34984) 	'CAT': [{}, {'depth': 6, 'grow_policy': 'SymmetricTree', 'l2_leaf_reg': 2.1542798306067823, 'learning_rate': 0.06864209415792857, 'max_ctr_complexity': 4, 'one_hot_max_size': 10, 'ag_args': {'name_suffix': '_r177', 'priority': -1}}, {'depth': 8, 'grow_policy': 'Depthwise', 'l2_leaf_reg': 2.7997999596449104, 'learning_rate': 0.031375015734637225, 'max_ctr_complexity': 2, 'one_hot_max_size': 3, 'ag_args': {'name_suffix': '_r9', 'priority': -5}}],
(_dystack pid=34984) 	'XGB': [{}, {'colsample_bytree': 0.6917311125174739, 'enable_categorical': False, 'learning_rate': 0.018063876087523967, 'max_depth': 10, 'min_child_weight': 0.6028633586934382, 'ag_args': {'name_suffix': '_r33', 'priority': -8}}, {'colsample_bytree': 0.6628423832084077, 'enable_categorical': False, 'learning_rate': 0.08775715546881824, 'max_depth': 5, 'min_child_weight': 0.6294123374222513, 'ag_args': {'name_suffix': '_r89', 'priority': -16}}],
(_dystack pid=34984) 	'FASTAI': [{}, {'bs': 256, 'emb_drop': 0.5411770367537934, 'epochs': 43, 'layers': [800, 400], 'lr': 0.01519848858318159, 'ps': 0.23782946566604385, 'ag_args': {'name_suffix': '_r191', 'priority': -4}}, {'bs': 2048, 'emb_drop': 0.05070411322605811, 'epochs': 29, 'layers': [200, 100], 'lr': 0.08974235041576624, 'ps': 0.10393466140748028, 'ag_args': {'name_suffix': '_r102', 'priority': -11}}],
(_dystack pid=34984) 	'RF': [{'criterion': 'gini', 'ag_args': {'name_suffix': 'Gini', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'entropy', 'ag_args': {'name_suffix': 'Entr', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'squared_error', 'ag_args': {'name_suffix': 'MSE', 'problem_types': ['regression', 'quantile']}}],
(_dystack pid=34984) 	'XT': [{'criterion': 'gini', 'ag_args': {'name_suffix': 'Gini', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'entropy', 'ag_args': {'name_suffix': 'Entr', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'squared_error', 'ag_args': {'name_suffix': 'MSE', 'problem_types': ['regression', 'quantile']}}],
(_dystack pid=34984) 	'KNN': [{'weights': 'uniform', 'ag_args': {'name_suffix': 'Unif'}}, {'weights': 'distance', 'ag_args': {'name_suffix': 'Dist'}}],
(_dystack pid=34984) }
(_dystack pid=34984) AutoGluon will fit 2 stack levels (L1 to L2) ...
(_dystack pid=34984) Fitting 108 L1 models, fit_strategy="sequential" ...
(_dystack pid=34984) Fitting model: KNeighborsUnif_BAG_L1 ... Training model for up to 594.27s of the 891.62s of remaining time.
(_dystack pid=34984) 	-4814.4279	 = Validation score   (-root_mean_squared_error)
(_dystack pid=34984) 	0.0s	 = Training   runtime
(_dystack pid=34984) 	0.02s	 = Validation runtime
(_dystack pid=34984) Fitting model: KNeighborsDist_BAG_L1 ... Training model for up to 593.10s of the 890.46s of remaining time.
(_dystack pid=34984) 	-5267.7908	 = Validation score   (-root_mean_squared_error)
(_dystack pid=34984) 	0.0s	 = Training   runtime
(_dystack pid=34984) 	0.01s	 = Validation runtime
(_dystack pid=34984) Fitting model: LightGBMXT_BAG_L1 ... Training model for up to 593.07s of the 890.42s of remaining time.
(_dystack pid=34984) 	Fitting 5 child models (S1F1 - S1F5) | Fitting with ParallelLocalFoldFittingStrategy (5 workers, per: cpus=4, gpus=0, memory=0.05%)

(_ray_fit pid=41728) [1000]	valid_set's rmse: 6360.24

(_dystack pid=34984) 	-3899.695	 = Validation score   (-root_mean_squared_error)
(_dystack pid=34984) 	0.96s	 = Training   runtime
(_dystack pid=34984) 	0.01s	 = Validation runtime
(_dystack pid=34984) Fitting model: LightGBM_BAG_L1 ... Training model for up to 590.18s of the 887.53s of remaining time.
(_dystack pid=34984) 	Fitting 5 child models (S1F1 - S1F5) | Fitting with ParallelLocalFoldFittingStrategy (5 workers, per: cpus=4, gpus=0, memory=0.05%)
(_dystack pid=34984) 	-3977.0755	 = Validation score   (-root_mean_squared_error)
(_dystack pid=34984) 	0.73s	 = Training   runtime
(_dystack pid=34984) 	0.01s	 = Validation runtime
(_dystack pid=34984) Fitting model: RandomForestMSE_BAG_L1 ... Training model for up to 587.51s of the 884.87s of remaining time.
(_dystack pid=34984) f:\car-project\.ds\Lib\site-packages\sklearn\base.py:474: FutureWarning: `BaseEstimator._validate_data` is deprecated in 1.6 and will be removed in 1.7. Use `sklearn.utils.validation.validate_data` instead. This function becomes public and is part of the scikit-learn developer API.
(_dystack pid=34984)   warnings.warn(
(_dystack pid=34984) 	-3388.8425	 = Validation score   (-root_mean_squared_error)
(_dystack pid=34984) 	0.42s	 = Training   runtime
(_dystack pid=34984) 	0.06s	 = Validation runtime
(_dystack pid=34984) Fitting model: CatBoost_BAG_L1 ... Training model for up to 586.99s of the 884.34s of remaining time.
(_dystack pid=34984) 	Fitting 5 child models (S1F1 - S1F5) | Fitting with ParallelLocalFoldFittingStrategy (5 workers, per: cpus=4, gpus=0, memory=3.24%)
(_ray_fit pid=38708) f:\car-project\.ds\Lib\site-packages\autogluon\common\utils\try_import.py:69: UserWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html. The pkg_resources package is slated for removal as early as 2025-11-30. Refrain from using this package or pin to Setuptools<81.
(_ray_fit pid=38708)   from pkg_resources import parse_version  # pylint: disable=import-outside-toplevel
(_dystack pid=34984) 	-3568.7922	 = Validation score   (-root_mean_squared_error)
(_dystack pid=34984) 	244.67s	 = Training   runtime
(_dystack pid=34984) 	0.01s	 = Validation runtime
(_dystack pid=34984) Fitting model: ExtraTreesMSE_BAG_L1 ... Training model for up to 340.39s of the 637.74s of remaining time.
(_ray_fit pid=38788) f:\car-project\.ds\Lib\site-packages\autogluon\common\utils\try_import.py:69: UserWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html. The pkg_resources package is slated for removal as early as 2025-11-30. Refrain from using this package or pin to Setuptools<81. [repeated 4x across cluster] (Ray deduplicates logs by default. Set RAY_DEDUP_LOGS=0 to disable log deduplication, or see https://docs.ray.io/en/master/ray-observability/user-guides/configure-logging.html#log-deduplication for more options.)
(_ray_fit pid=38788)   from pkg_resources import parse_version  # pylint: disable=import-outside-toplevel [repeated 4x across cluster]
(_dystack pid=34984) f:\car-project\.ds\Lib\site-packages\sklearn\base.py:474: FutureWarning: `BaseEstimator._validate_data` is deprecated in 1.6 and will be removed in 1.7. Use `sklearn.utils.validation.validate_data` instead. This function becomes public and is part of the scikit-learn developer API.
(_dystack pid=34984)   warnings.warn(
(_dystack pid=34984) 	-3365.516	 = Validation score   (-root_mean_squared_error)
(_dystack pid=34984) 	0.3s	 = Training   runtime
(_dystack pid=34984) 	0.05s	 = Validation runtime
(_dystack pid=34984) Fitting model: NeuralNetFastAI_BAG_L1 ... Training model for up to 340.01s of the 637.36s of remaining time.
(_dystack pid=34984) 	Fitting 5 child models (S1F1 - S1F5) | Fitting with ParallelLocalFoldFittingStrategy (5 workers, per: cpus=4, gpus=0, memory=0.01%)
(_dystack pid=34984) 	-4086.5866	 = Validation score   (-root_mean_squared_error)
(_dystack pid=34984) 	2.34s	 = Training   runtime
(_dystack pid=34984) 	0.03s	 = Validation runtime
(_dystack pid=34984) Fitting model: XGBoost_BAG_L1 ... Training model for up to 335.64s of the 632.99s of remaining time.
(_dystack pid=34984) 	Fitting 5 child models (S1F1 - S1F5) | Fitting with ParallelLocalFoldFittingStrategy (5 workers, per: cpus=4, gpus=0, memory=0.08%)
(_ray_fit pid=39452) f:\car-project\.ds\Lib\site-packages\autogluon\common\utils\try_import.py:107: UserWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html. The pkg_resources package is slated for removal as early as 2025-11-30. Refrain from using this package or pin to Setuptools<81. [repeated 6x across cluster]
(_ray_fit pid=39452)   from pkg_resources import parse_version  # pylint: disable=import-outside-toplevel [repeated 6x across cluster]
(_dystack pid=34984) 	-4168.5506	 = Validation score   (-root_mean_squared_error)
(_dystack pid=34984) 	1.51s	 = Training   runtime
(_dystack pid=34984) 	0.02s	 = Validation runtime
(_dystack pid=34984) Fitting model: NeuralNetTorch_BAG_L1 ... Training model for up to 332.07s of the 629.43s of remaining time.
(_dystack pid=34984) 	Fitting 5 child models (S1F1 - S1F5) | Fitting with ParallelLocalFoldFittingStrategy (5 workers, per: cpus=4, gpus=0, memory=0.00%)
(_dystack pid=34984) 	-4314.2812	 = Validation score   (-root_mean_squared_error)
(_dystack pid=34984) 	11.99s	 = Training   runtime
(_dystack pid=34984) 	0.03s	 = Validation runtime
(_dystack pid=34984) Fitting model: LightGBMLarge_BAG_L1 ... Training model for up to 318.17s of the 615.52s of remaining time.
(_dystack pid=34984) 	Fitting 5 child models (S1F1 - S1F5) | Fitting with ParallelLocalFoldFittingStrategy (5 workers, per: cpus=4, gpus=0, memory=0.20%)
(_ray_fit pid=11964) f:\car-project\.ds\Lib\site-packages\autogluon\common\utils\try_import.py:107: UserWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html. The pkg_resources package is slated for removal as early as 2025-11-30. Refrain from using this package or pin to Setuptools<81. [repeated 4x across cluster]
(_ray_fit pid=11964)   from pkg_resources import parse_version  # pylint: disable=import-outside-toplevel [repeated 4x across cluster]

(_ray_fit pid=11056) [1000]	valid_set's rmse: 2503.05
(_ray_fit pid=11056) [2000]	valid_set's rmse: 2502.67

(_dystack pid=34984) 	-4267.5891	 = Validation score   (-root_mean_squared_error)
(_dystack pid=34984) 	3.93s	 = Training   runtime
(_dystack pid=34984) 	0.01s	 = Validation runtime
(_dystack pid=34984) Fitting model: CatBoost_r177_BAG_L1 ... Training model for up to 312.10s of the 609.45s of remaining time.
(_dystack pid=34984) 	Fitting 5 child models (S1F1 - S1F5) | Fitting with ParallelLocalFoldFittingStrategy (5 workers, per: cpus=4, gpus=0, memory=3.07%)
(_ray_fit pid=41732) f:\car-project\.ds\Lib\site-packages\autogluon\common\utils\try_import.py:69: UserWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html. The pkg_resources package is slated for removal as early as 2025-11-30. Refrain from using this package or pin to Setuptools<81.
(_ray_fit pid=41732)   from pkg_resources import parse_version  # pylint: disable=import-outside-toplevel
(_dystack pid=34984) 	-3584.336	 = Validation score   (-root_mean_squared_error)
(_dystack pid=34984) 	76.67s	 = Training   runtime
(_dystack pid=34984) 	0.01s	 = Validation runtime
(_dystack pid=34984) Fitting model: NeuralNetTorch_r79_BAG_L1 ... Training model for up to 233.52s of the 530.87s of remaining time.
(_dystack pid=34984) 	Fitting 5 child models (S1F1 - S1F5) | Fitting with ParallelLocalFoldFittingStrategy (5 workers, per: cpus=4, gpus=0, memory=0.00%)
(_ray_fit pid=34508) f:\car-project\.ds\Lib\site-packages\autogluon\common\utils\try_import.py:69: UserWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html. The pkg_resources package is slated for removal as early as 2025-11-30. Refrain from using this package or pin to Setuptools<81. [repeated 4x across cluster]
(_ray_fit pid=34508)   from pkg_resources import parse_version  # pylint: disable=import-outside-toplevel [repeated 4x across cluster]
(_dystack pid=34984) 	-3740.2964	 = Validation score   (-root_mean_squared_error)
(_dystack pid=34984) 	16.3s	 = Training   runtime
(_dystack pid=34984) 	0.03s	 = Validation runtime
(_dystack pid=34984) Fitting model: LightGBM_r131_BAG_L1 ... Training model for up to 215.28s of the 512.63s of remaining time.
(_dystack pid=34984) 	Fitting 5 child models (S1F1 - S1F5) | Fitting with ParallelLocalFoldFittingStrategy (5 workers, per: cpus=4, gpus=0, memory=0.08%)

(_ray_fit pid=37136) [1000]	valid_set's rmse: 2228.69
(_ray_fit pid=32952) [1000]	valid_set's rmse: 6457.98

(_dystack pid=34984) 	-4080.8508	 = Validation score   (-root_mean_squared_error)
(_dystack pid=34984) 	1.16s	 = Training   runtime
(_dystack pid=34984) 	0.01s	 = Validation runtime
(_dystack pid=34984) Fitting model: NeuralNetFastAI_r191_BAG_L1 ... Training model for up to 212.16s of the 509.51s of remaining time.
(_dystack pid=34984) 	Fitting 5 child models (S1F1 - S1F5) | Fitting with ParallelLocalFoldFittingStrategy (5 workers, per: cpus=4, gpus=0, memory=0.01%)
(_ray_fit pid=31724) f:\car-project\.ds\Lib\site-packages\autogluon\common\utils\try_import.py:131: UserWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html. The pkg_resources package is slated for removal as early as 2025-11-30. Refrain from using this package or pin to Setuptools<81.
(_ray_fit pid=31724)   from pkg_resources import parse_version  # pylint: disable=import-outside-toplevel
(_dystack pid=34984) 	-3647.3385	 = Validation score   (-root_mean_squared_error)
(_dystack pid=34984) 	2.85s	 = Training   runtime
(_dystack pid=34984) 	0.03s	 = Validation runtime
(_dystack pid=34984) Fitting model: CatBoost_r9_BAG_L1 ... Training model for up to 207.34s of the 504.69s of remaining time.
(_dystack pid=34984) 	Fitting 5 child models (S1F1 - S1F5) | Fitting with ParallelLocalFoldFittingStrategy (5 workers, per: cpus=4, gpus=0, memory=3.55%)
(_ray_fit pid=40480) f:\car-project\.ds\Lib\site-packages\autogluon\common\utils\try_import.py:69: UserWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html. The pkg_resources package is slated for removal as early as 2025-11-30. Refrain from using this package or pin to Setuptools<81. [repeated 9x across cluster]
(_ray_fit pid=40480)   from pkg_resources import parse_version  # pylint: disable=import-outside-toplevel [repeated 9x across cluster]
(_ray_fit pid=34404) 	Ran out of time, early stopping on iteration 3882.
(_dystack pid=34984) 	-3733.7134	 = Validation score   (-root_mean_squared_error)
(_dystack pid=34984) 	166.23s	 = Training   runtime
(_dystack pid=34984) 	0.02s	 = Validation runtime
(_dystack pid=34984) Fitting model: LightGBM_r96_BAG_L1 ... Training model for up to 39.06s of the 336.41s of remaining time.
(_dystack pid=34984) 	Fitting 5 child models (S1F1 - S1F5) | Fitting with ParallelLocalFoldFittingStrategy (5 workers, per: cpus=4, gpus=0, memory=0.03%)

(_ray_fit pid=35168) [1000]	valid_set's rmse: 3989.11
(_ray_fit pid=29280) [1000]	valid_set's rmse: 2663.6

(_dystack pid=34984) 	-4064.0372	 = Validation score   (-root_mean_squared_error)
(_dystack pid=34984) 	3.29s	 = Training   runtime
(_dystack pid=34984) 	0.02s	 = Validation runtime
(_dystack pid=34984) Fitting model: NeuralNetTorch_r22_BAG_L1 ... Training model for up to 33.73s of the 331.09s of remaining time.
(_dystack pid=34984) 	Fitting 5 child models (S1F1 - S1F5) | Fitting with ParallelLocalFoldFittingStrategy (5 workers, per: cpus=4, gpus=0, memory=0.00%)
(_dystack pid=34984) 	-3483.0191	 = Validation score   (-root_mean_squared_error)
(_dystack pid=34984) 	11.34s	 = Training   runtime
(_dystack pid=34984) 	0.03s	 = Validation runtime
(_dystack pid=34984) Fitting model: XGBoost_r33_BAG_L1 ... Training model for up to 20.48s of the 317.84s of remaining time.
(_dystack pid=34984) 	Fitting 5 child models (S1F1 - S1F5) | Fitting with ParallelLocalFoldFittingStrategy (5 workers, per: cpus=4, gpus=0, memory=0.43%)
(_ray_fit pid=30628) f:\car-project\.ds\Lib\site-packages\autogluon\common\utils\try_import.py:107: UserWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html. The pkg_resources package is slated for removal as early as 2025-11-30. Refrain from using this package or pin to Setuptools<81.
(_ray_fit pid=30628)   from pkg_resources import parse_version  # pylint: disable=import-outside-toplevel
(_dystack pid=34984) 	-4047.8579	 = Validation score   (-root_mean_squared_error)
(_dystack pid=34984) 	11.26s	 = Training   runtime
(_dystack pid=34984) 	0.05s	 = Validation runtime
(_dystack pid=34984) Fitting model: ExtraTrees_r42_BAG_L1 ... Training model for up to 7.13s of the 304.49s of remaining time.
(_ray_fit pid=23372) f:\car-project\.ds\Lib\site-packages\autogluon\common\utils\try_import.py:107: UserWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html. The pkg_resources package is slated for removal as early as 2025-11-30. Refrain from using this package or pin to Setuptools<81. [repeated 4x across cluster]
(_ray_fit pid=23372)   from pkg_resources import parse_version  # pylint: disable=import-outside-toplevel [repeated 4x across cluster]
(_dystack pid=34984) f:\car-project\.ds\Lib\site-packages\sklearn\base.py:474: FutureWarning: `BaseEstimator._validate_data` is deprecated in 1.6 and will be removed in 1.7. Use `sklearn.utils.validation.validate_data` instead. This function becomes public and is part of the scikit-learn developer API.
(_dystack pid=34984)   warnings.warn(
(_dystack pid=34984) 	-3407.8514	 = Validation score   (-root_mean_squared_error)
(_dystack pid=34984) 	0.32s	 = Training   runtime
(_dystack pid=34984) 	0.05s	 = Validation runtime
(_dystack pid=34984) Fitting model: CatBoost_r137_BAG_L1 ... Training model for up to 6.74s of the 304.09s of remaining time.
(_dystack pid=34984) 	Fitting 5 child models (S1F1 - S1F5) | Fitting with ParallelLocalFoldFittingStrategy (5 workers, per: cpus=4, gpus=0, memory=2.92%)
(_ray_fit pid=38752) 	Ran out of time, early stopping on iteration 165.
(_ray_fit pid=34612) f:\car-project\.ds\Lib\site-packages\autogluon\common\utils\try_import.py:69: UserWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html. The pkg_resources package is slated for removal as early as 2025-11-30. Refrain from using this package or pin to Setuptools<81. [repeated 5x across cluster]
(_ray_fit pid=34612)   from pkg_resources import parse_version  # pylint: disable=import-outside-toplevel [repeated 5x across cluster]
(_dystack pid=34984) 	-3802.933	 = Validation score   (-root_mean_squared_error)
(_dystack pid=34984) 	5.35s	 = Training   runtime
(_dystack pid=34984) 	0.01s	 = Validation runtime
(_dystack pid=34984) Fitting model: WeightedEnsemble_L2 ... Training model for up to 360.00s of the 296.67s of remaining time.
(_dystack pid=34984) 	Ensemble Weights: {'RandomForestMSE_BAG_L1': 0.48, 'NeuralNetTorch_r22_BAG_L1': 0.44, 'ExtraTreesMSE_BAG_L1': 0.04, 'NeuralNetFastAI_r191_BAG_L1': 0.04}
(_dystack pid=34984) 	-3104.2783	 = Validation score   (-root_mean_squared_error)
(_dystack pid=34984) 	0.01s	 = Training   runtime
(_dystack pid=34984) 	0.0s	 = Validation runtime
(_dystack pid=34984) Fitting 106 L2 models, fit_strategy="sequential" ...
(_dystack pid=34984) Fitting model: LightGBMXT_BAG_L2 ... Training model for up to 296.65s of the 296.62s of remaining time.
(_dystack pid=34984) 	Fitting 5 child models (S1F1 - S1F5) | Fitting with ParallelLocalFoldFittingStrategy (5 workers, per: cpus=4, gpus=0, memory=0.08%)

(_ray_fit pid=11468) [1000]	valid_set's rmse: 3796.55 [repeated 11x across cluster]

(_dystack pid=34984) 	-3277.6635	 = Validation score   (-root_mean_squared_error)
(_dystack pid=34984) 	1.91s	 = Training   runtime
(_dystack pid=34984) 	0.02s	 = Validation runtime
(_dystack pid=34984) Fitting model: LightGBM_BAG_L2 ... Training model for up to 292.75s of the 292.72s of remaining time.
(_dystack pid=34984) 	Fitting 5 child models (S1F1 - S1F5) | Fitting with ParallelLocalFoldFittingStrategy (5 workers, per: cpus=4, gpus=0, memory=0.08%)
(_dystack pid=34984) 	-3055.4649	 = Validation score   (-root_mean_squared_error)
(_dystack pid=34984) 	1.37s	 = Training   runtime
(_dystack pid=34984) 	0.01s	 = Validation runtime
(_dystack pid=34984) Fitting model: RandomForestMSE_BAG_L2 ... Training model for up to 289.40s of the 289.37s of remaining time.
(_ray_fit pid=34612) 	Ran out of time, early stopping on iteration 165. [repeated 4x across cluster]
(_dystack pid=34984) f:\car-project\.ds\Lib\site-packages\sklearn\base.py:474: FutureWarning: `BaseEstimator._validate_data` is deprecated in 1.6 and will be removed in 1.7. Use `sklearn.utils.validation.validate_data` instead. This function becomes public and is part of the scikit-learn developer API.
(_dystack pid=34984)   warnings.warn(
(_dystack pid=34984) 	-3132.4088	 = Validation score   (-root_mean_squared_error)
(_dystack pid=34984) 	0.32s	 = Training   runtime
(_dystack pid=34984) 	0.05s	 = Validation runtime
(_dystack pid=34984) Fitting model: CatBoost_BAG_L2 ... Training model for up to 289.00s of the 288.97s of remaining time.
(_dystack pid=34984) 	Fitting 5 child models (S1F1 - S1F5) | Fitting with ParallelLocalFoldFittingStrategy (5 workers, per: cpus=4, gpus=0, memory=3.12%)
(_ray_fit pid=12500) f:\car-project\.ds\Lib\site-packages\autogluon\common\utils\try_import.py:69: UserWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html. The pkg_resources package is slated for removal as early as 2025-11-30. Refrain from using this package or pin to Setuptools<81.
(_ray_fit pid=12500)   from pkg_resources import parse_version  # pylint: disable=import-outside-toplevel
(_dystack pid=34984) 	-3205.5664	 = Validation score   (-root_mean_squared_error)
(_dystack pid=34984) 	49.12s	 = Training   runtime
(_dystack pid=34984) 	0.01s	 = Validation runtime
(_dystack pid=34984) Fitting model: ExtraTreesMSE_BAG_L2 ... Training model for up to 237.95s of the 237.92s of remaining time.
(_ray_fit pid=41432) f:\car-project\.ds\Lib\site-packages\autogluon\common\utils\try_import.py:69: UserWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html. The pkg_resources package is slated for removal as early as 2025-11-30. Refrain from using this package or pin to Setuptools<81. [repeated 4x across cluster]
(_ray_fit pid=41432)   from pkg_resources import parse_version  # pylint: disable=import-outside-toplevel [repeated 4x across cluster]
(_dystack pid=34984) f:\car-project\.ds\Lib\site-packages\sklearn\base.py:474: FutureWarning: `BaseEstimator._validate_data` is deprecated in 1.6 and will be removed in 1.7. Use `sklearn.utils.validation.validate_data` instead. This function becomes public and is part of the scikit-learn developer API.
(_dystack pid=34984)   warnings.warn(
(_dystack pid=34984) 	-3064.1326	 = Validation score   (-root_mean_squared_error)
(_dystack pid=34984) 	0.31s	 = Training   runtime
(_dystack pid=34984) 	0.05s	 = Validation runtime
(_dystack pid=34984) Fitting model: NeuralNetFastAI_BAG_L2 ... Training model for up to 237.55s of the 237.53s of remaining time.
(_dystack pid=34984) 	Fitting 5 child models (S1F1 - S1F5) | Fitting with ParallelLocalFoldFittingStrategy (5 workers, per: cpus=4, gpus=0, memory=0.01%)
(_dystack pid=34984) 	-3264.5106	 = Validation score   (-root_mean_squared_error)
(_dystack pid=34984) 	2.22s	 = Training   runtime
(_dystack pid=34984) 	0.03s	 = Validation runtime
(_dystack pid=34984) Fitting model: XGBoost_BAG_L2 ... Training model for up to 233.26s of the 233.23s of remaining time.
(_dystack pid=34984) 	Fitting 5 child models (S1F1 - S1F5) | Fitting with ParallelLocalFoldFittingStrategy (5 workers, per: cpus=4, gpus=0, memory=0.15%)
(_ray_fit pid=39712) f:\car-project\.ds\Lib\site-packages\autogluon\common\utils\try_import.py:107: UserWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html. The pkg_resources package is slated for removal as early as 2025-11-30. Refrain from using this package or pin to Setuptools<81. [repeated 6x across cluster]
(_ray_fit pid=39712)   from pkg_resources import parse_version  # pylint: disable=import-outside-toplevel [repeated 6x across cluster]
(_dystack pid=34984) 	-3450.4273	 = Validation score   (-root_mean_squared_error)
(_dystack pid=34984) 	1.05s	 = Training   runtime
(_dystack pid=34984) 	0.02s	 = Validation runtime
(_dystack pid=34984) Fitting model: NeuralNetTorch_BAG_L2 ... Training model for up to 230.12s of the 230.10s of remaining time.
(_dystack pid=34984) 	Fitting 5 child models (S1F1 - S1F5) | Fitting with ParallelLocalFoldFittingStrategy (5 workers, per: cpus=4, gpus=0, memory=0.01%)
(_dystack pid=34984) 	-3998.7406	 = Validation score   (-root_mean_squared_error)
(_dystack pid=34984) 	6.56s	 = Training   runtime
(_dystack pid=34984) 	0.03s	 = Validation runtime
(_dystack pid=34984) Fitting model: LightGBMLarge_BAG_L2 ... Training model for up to 221.60s of the 221.57s of remaining time.
(_dystack pid=34984) 	Fitting 5 child models (S1F1 - S1F5) | Fitting with ParallelLocalFoldFittingStrategy (5 workers, per: cpus=4, gpus=0, memory=0.31%)
(_ray_fit pid=37196) f:\car-project\.ds\Lib\site-packages\autogluon\common\utils\try_import.py:107: UserWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html. The pkg_resources package is slated for removal as early as 2025-11-30. Refrain from using this package or pin to Setuptools<81. [repeated 4x across cluster]
(_ray_fit pid=37196)   from pkg_resources import parse_version  # pylint: disable=import-outside-toplevel [repeated 4x across cluster]

(_ray_fit pid=35560) [1000]	valid_set's rmse: 3154.67 [repeated 4x across cluster]

(_dystack pid=34984) 	-3379.4168	 = Validation score   (-root_mean_squared_error)
(_dystack pid=34984) 	4.8s	 = Training   runtime
(_dystack pid=34984) 	0.02s	 = Validation runtime
(_dystack pid=34984) Fitting model: CatBoost_r177_BAG_L2 ... Training model for up to 214.65s of the 214.62s of remaining time.
(_dystack pid=34984) 	Fitting 5 child models (S1F1 - S1F5) | Fitting with ParallelLocalFoldFittingStrategy (5 workers, per: cpus=4, gpus=0, memory=3.09%)
(_ray_fit pid=37976) f:\car-project\.ds\Lib\site-packages\autogluon\common\utils\try_import.py:69: UserWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html. The pkg_resources package is slated for removal as early as 2025-11-30. Refrain from using this package or pin to Setuptools<81.
(_ray_fit pid=37976)   from pkg_resources import parse_version  # pylint: disable=import-outside-toplevel
(_dystack pid=34984) 	-3217.739	 = Validation score   (-root_mean_squared_error)
(_dystack pid=34984) 	24.72s	 = Training   runtime
(_dystack pid=34984) 	0.01s	 = Validation runtime
(_dystack pid=34984) Fitting model: NeuralNetTorch_r79_BAG_L2 ... Training model for up to 188.02s of the 187.99s of remaining time.
(_dystack pid=34984) 	Fitting 5 child models (S1F1 - S1F5) | Fitting with ParallelLocalFoldFittingStrategy (5 workers, per: cpus=4, gpus=0, memory=0.00%)
(_ray_fit pid=29308) f:\car-project\.ds\Lib\site-packages\autogluon\common\utils\try_import.py:69: UserWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html. The pkg_resources package is slated for removal as early as 2025-11-30. Refrain from using this package or pin to Setuptools<81. [repeated 4x across cluster]
(_ray_fit pid=29308)   from pkg_resources import parse_version  # pylint: disable=import-outside-toplevel [repeated 4x across cluster]
(_dystack pid=34984) 	-3742.5378	 = Validation score   (-root_mean_squared_error)
(_dystack pid=34984) 	5.68s	 = Training   runtime
(_dystack pid=34984) 	0.04s	 = Validation runtime
(_dystack pid=34984) Fitting model: LightGBM_r131_BAG_L2 ... Training model for up to 180.42s of the 180.39s of remaining time.
(_dystack pid=34984) 	Fitting 5 child models (S1F1 - S1F5) | Fitting with ParallelLocalFoldFittingStrategy (5 workers, per: cpus=4, gpus=0, memory=0.13%)

(_ray_fit pid=39804) [1000]	valid_set's rmse: 3495.3 [repeated 3x across cluster]
(_ray_fit pid=19852) [9000]	valid_set's rmse: 2669.53 [repeated 16x across cluster]

(_dystack pid=34984) 	-2811.9831	 = Validation score   (-root_mean_squared_error)
(_dystack pid=34984) 	7.24s	 = Training   runtime
(_dystack pid=34984) 	0.05s	 = Validation runtime
(_dystack pid=34984) Fitting model: NeuralNetFastAI_r191_BAG_L2 ... Training model for up to 170.95s of the 170.92s of remaining time.
(_dystack pid=34984) 	Fitting 5 child models (S1F1 - S1F5) | Fitting with ParallelLocalFoldFittingStrategy (5 workers, per: cpus=4, gpus=0, memory=0.01%)
(_ray_fit pid=35708) f:\car-project\.ds\Lib\site-packages\autogluon\common\utils\try_import.py:131: UserWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html. The pkg_resources package is slated for removal as early as 2025-11-30. Refrain from using this package or pin to Setuptools<81.
(_ray_fit pid=35708)   from pkg_resources import parse_version  # pylint: disable=import-outside-toplevel
(_ray_fit pid=35708) No improvement since epoch 8: early stopping
(_dystack pid=34984) 	-3061.0314	 = Validation score   (-root_mean_squared_error)
(_dystack pid=34984) 	2.51s	 = Training   runtime
(_dystack pid=34984) 	0.03s	 = Validation runtime
(_dystack pid=34984) Fitting model: CatBoost_r9_BAG_L2 ... Training model for up to 166.52s of the 166.49s of remaining time.
(_dystack pid=34984) 	Fitting 5 child models (S1F1 - S1F5) | Fitting with ParallelLocalFoldFittingStrategy (5 workers, per: cpus=4, gpus=0, memory=3.74%)
(_dystack pid=34984) 	-3474.9983	 = Validation score   (-root_mean_squared_error)
(_dystack pid=34984) 	50.39s	 = Training   runtime
(_dystack pid=34984) 	0.01s	 = Validation runtime
(_dystack pid=34984) Fitting model: LightGBM_r96_BAG_L2 ... Training model for up to 114.11s of the 114.09s of remaining time.
(_dystack pid=34984) 	Fitting 5 child models (S1F1 - S1F5) | Fitting with ParallelLocalFoldFittingStrategy (5 workers, per: cpus=4, gpus=0, memory=0.04%)
(_ray_fit pid=38660) f:\car-project\.ds\Lib\site-packages\autogluon\common\utils\try_import.py:69: UserWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html. The pkg_resources package is slated for removal as early as 2025-11-30. Refrain from using this package or pin to Setuptools<81. [repeated 9x across cluster]
(_ray_fit pid=38660)   from pkg_resources import parse_version  # pylint: disable=import-outside-toplevel [repeated 9x across cluster]
(_ray_fit pid=36608) No improvement since epoch 20: early stopping [repeated 4x across cluster]

(_ray_fit pid=37456) [1000]	valid_set's rmse: 3660.9 [repeated 4x across cluster]

(_dystack pid=34984) 	-3565.6969	 = Validation score   (-root_mean_squared_error)
(_dystack pid=34984) 	4.93s	 = Training   runtime
(_dystack pid=34984) 	0.02s	 = Validation runtime
(_dystack pid=34984) Fitting model: NeuralNetTorch_r22_BAG_L2 ... Training model for up to 107.13s of the 107.11s of remaining time.
(_dystack pid=34984) 	Fitting 5 child models (S1F1 - S1F5) | Fitting with ParallelLocalFoldFittingStrategy (5 workers, per: cpus=4, gpus=0, memory=0.00%)
(_dystack pid=34984) 	-3666.6337	 = Validation score   (-root_mean_squared_error)
(_dystack pid=34984) 	6.11s	 = Training   runtime
(_dystack pid=34984) 	0.04s	 = Validation runtime
(_dystack pid=34984) Fitting model: XGBoost_r33_BAG_L2 ... Training model for up to 99.10s of the 99.07s of remaining time.
(_dystack pid=34984) 	Fitting 5 child models (S1F1 - S1F5) | Fitting with ParallelLocalFoldFittingStrategy (5 workers, per: cpus=4, gpus=0, memory=0.90%)
(_ray_fit pid=40532) f:\car-project\.ds\Lib\site-packages\autogluon\common\utils\try_import.py:107: UserWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html. The pkg_resources package is slated for removal as early as 2025-11-30. Refrain from using this package or pin to Setuptools<81.
(_ray_fit pid=40532)   from pkg_resources import parse_version  # pylint: disable=import-outside-toplevel
(_dystack pid=34984) 	-3387.3394	 = Validation score   (-root_mean_squared_error)
(_dystack pid=34984) 	4.96s	 = Training   runtime
(_dystack pid=34984) 	0.02s	 = Validation runtime
(_dystack pid=34984) Fitting model: ExtraTrees_r42_BAG_L2 ... Training model for up to 92.15s of the 92.13s of remaining time.
(_ray_fit pid=40468) f:\car-project\.ds\Lib\site-packages\autogluon\common\utils\try_import.py:107: UserWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html. The pkg_resources package is slated for removal as early as 2025-11-30. Refrain from using this package or pin to Setuptools<81. [repeated 4x across cluster]
(_ray_fit pid=40468)   from pkg_resources import parse_version  # pylint: disable=import-outside-toplevel [repeated 4x across cluster]
(_dystack pid=34984) f:\car-project\.ds\Lib\site-packages\sklearn\base.py:474: FutureWarning: `BaseEstimator._validate_data` is deprecated in 1.6 and will be removed in 1.7. Use `sklearn.utils.validation.validate_data` instead. This function becomes public and is part of the scikit-learn developer API.
(_dystack pid=34984)   warnings.warn(
(_dystack pid=34984) 	-3001.73	 = Validation score   (-root_mean_squared_error)
(_dystack pid=34984) 	0.32s	 = Training   runtime
(_dystack pid=34984) 	0.05s	 = Validation runtime
(_dystack pid=34984) Fitting model: CatBoost_r137_BAG_L2 ... Training model for up to 91.74s of the 91.72s of remaining time.
(_dystack pid=34984) 	Fitting 5 child models (S1F1 - S1F5) | Fitting with ParallelLocalFoldFittingStrategy (5 workers, per: cpus=4, gpus=0, memory=2.87%)
(_dystack pid=34984) 	-2996.5859	 = Validation score   (-root_mean_squared_error)
(_dystack pid=34984) 	27.31s	 = Training   runtime
(_dystack pid=34984) 	0.01s	 = Validation runtime
(_dystack pid=34984) Fitting model: NeuralNetFastAI_r102_BAG_L2 ... Training model for up to 62.56s of the 62.53s of remaining time.
(_dystack pid=34984) 	Fitting 5 child models (S1F1 - S1F5) | Fitting with ParallelLocalFoldFittingStrategy (5 workers, per: cpus=4, gpus=0, memory=0.01%)
(_ray_fit pid=39876) f:\car-project\.ds\Lib\site-packages\autogluon\common\utils\try_import.py:69: UserWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html. The pkg_resources package is slated for removal as early as 2025-11-30. Refrain from using this package or pin to Setuptools<81. [repeated 5x across cluster]
(_ray_fit pid=39876)   from pkg_resources import parse_version  # pylint: disable=import-outside-toplevel [repeated 5x across cluster]
(_ray_fit pid=41808) No improvement since epoch 0: early stopping
(_ray_fit pid=39832) f:\car-project\.ds\Lib\site-packages\autogluon\common\utils\try_import.py:131: UserWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html. The pkg_resources package is slated for removal as early as 2025-11-30. Refrain from using this package or pin to Setuptools<81. [repeated 5x across cluster]
(_ray_fit pid=39832)   from pkg_resources import parse_version  # pylint: disable=import-outside-toplevel [repeated 5x across cluster]
(_dystack pid=34984) 	-3281.5803	 = Validation score   (-root_mean_squared_error)
(_dystack pid=34984) 	3.85s	 = Training   runtime
(_dystack pid=34984) 	0.04s	 = Validation runtime
(_dystack pid=34984) Fitting model: CatBoost_r13_BAG_L2 ... Training model for up to 56.67s of the 56.64s of remaining time.
(_dystack pid=34984) 	Fitting 5 child models (S1F1 - S1F5) | Fitting with ParallelLocalFoldFittingStrategy (5 workers, per: cpus=4, gpus=0, memory=3.71%)
(_ray_fit pid=39668) 	Ran out of time, early stopping on iteration 742.
(_ray_fit pid=23900) No improvement since epoch 2: early stopping [repeated 3x across cluster]
(_ray_fit pid=35036) f:\car-project\.ds\Lib\site-packages\autogluon\common\utils\try_import.py:69: UserWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html. The pkg_resources package is slated for removal as early as 2025-11-30. Refrain from using this package or pin to Setuptools<81. [repeated 5x across cluster]
(_ray_fit pid=35036)   from pkg_resources import parse_version  # pylint: disable=import-outside-toplevel [repeated 5x across cluster]
(_dystack pid=34984) 	-3326.5714	 = Validation score   (-root_mean_squared_error)
(_dystack pid=34984) 	45.31s	 = Training   runtime
(_dystack pid=34984) 	0.02s	 = Validation runtime
(_dystack pid=34984) Fitting model: RandomForest_r195_BAG_L2 ... Training model for up to 9.33s of the 9.31s of remaining time.
(_dystack pid=34984) f:\car-project\.ds\Lib\site-packages\sklearn\base.py:474: FutureWarning: `BaseEstimator._validate_data` is deprecated in 1.6 and will be removed in 1.7. Use `sklearn.utils.validation.validate_data` instead. This function becomes public and is part of the scikit-learn developer API.
(_dystack pid=34984)   warnings.warn(
(_dystack pid=34984) 	-3114.4043	 = Validation score   (-root_mean_squared_error)
(_dystack pid=34984) 	0.49s	 = Training   runtime
(_dystack pid=34984) 	0.05s	 = Validation runtime
(_dystack pid=34984) Fitting model: WeightedEnsemble_L3 ... Training model for up to 360.00s of the 8.49s of remaining time.
(_dystack pid=34984) 	Ensemble Weights: {'LightGBM_r131_BAG_L2': 0.773, 'NeuralNetFastAI_r191_BAG_L2': 0.182, 'NeuralNetTorch_r22_BAG_L1': 0.045}
(_dystack pid=34984) 	-2794.1503	 = Validation score   (-root_mean_squared_error)
(_dystack pid=34984) 	0.01s	 = Training   runtime
(_dystack pid=34984) 	0.0s	 = Validation runtime
(_dystack pid=34984) AutoGluon training complete, total runtime = 883.23s ... Best model: WeightedEnsemble_L3 | Estimated inference throughput: 448.3 rows/s (106 batch size)
(_dystack pid=34984) TabularPredictor saved. To load, use: predictor = TabularPredictor.load("f:\car-project\AutogluonModels\ag-20250725_012410\ds_sub_fit\sub_fit_ho")
(_dystack pid=34984) Deleting DyStack predictor artifacts (clean_up_fits=True) ...
Leaderboard on holdout data (DyStack):
                          model  score_holdout    score_val              eval_metric  pred_time_test  pred_time_val    fit_time  pred_time_test_marginal  pred_time_val_marginal  fit_time_marginal  stack_level  can_infer  fit_order
0     NeuralNetTorch_r22_BAG_L1   -2510.200749 -3483.019110  root_mean_squared_error        0.054000       0.030500   11.343105                 0.054000                0.030500          11.343105            1       True         18
1               CatBoost_BAG_L1   -2653.261346 -3568.792210  root_mean_squared_error        0.237525       0.013000  244.667631                 0.237525                0.013000         244.667631            1       True          6
2         NeuralNetTorch_BAG_L1   -2657.245784 -4314.281155  root_mean_squared_error        0.053503       0.026002   11.986740                 0.053503                0.026002          11.986740            1       True         10
3          CatBoost_r177_BAG_L1   -2659.362427 -3584.335951  root_mean_squared_error        0.022500       0.010501   76.666590                 0.022500                0.010501          76.666590            1       True         12
4          CatBoost_r137_BAG_L1   -2754.300262 -3802.932972  root_mean_squared_error        0.013005       0.010507    5.350978                 0.013005                0.010507           5.350978            1       True         21
5           WeightedEnsemble_L2   -2762.156668 -3104.278304  root_mean_squared_error        0.224881       0.165610   14.919998                 0.002000                0.000000           0.009000            2       True         22
6            XGBoost_r33_BAG_L1   -2799.382812 -4047.857884  root_mean_squared_error        0.472496       0.046499   11.259696                 0.472496                0.046499          11.259696            1       True         19
7          LightGBM_r131_BAG_L1   -2815.052132 -4080.850828  root_mean_squared_error        0.034500       0.014002    1.155810                 0.034500                0.014002           1.155810            1       True         14
8                XGBoost_BAG_L1   -2836.252948 -4168.550601  root_mean_squared_error        0.202046       0.019500    1.512635                 0.202046                0.019500           1.512635            1       True          9
9   NeuralNetFastAI_r102_BAG_L2   -2906.846396 -3281.580276  root_mean_squared_error        1.111428       0.296681  275.654455                 0.045000                0.042004           3.849567            2       True         42
10         LightGBMLarge_BAG_L1   -2915.137826 -4267.589053  root_mean_squared_error        0.078005       0.014521    3.929120                 0.078005                0.014521           3.929120            1       True         11
11        NeuralNetTorch_BAG_L2   -2921.623237 -3998.740580  root_mean_squared_error        1.132928       0.289176  278.362803                 0.066501                0.034499           6.557914            2       True         30
12    NeuralNetTorch_r79_BAG_L1   -2921.772079 -3740.296386  root_mean_squared_error        0.061007       0.030007   16.296525                 0.061007                0.030007          16.296525            1       True         13
13           CatBoost_r9_BAG_L1   -2937.652989 -3733.713418  root_mean_squared_error        0.058502       0.021503  166.229307                 0.058502                0.021503         166.229307            1       True         16
14          WeightedEnsemble_L3   -2963.616656 -2794.150337  root_mean_squared_error        1.310563       0.335686  281.571960                 0.001501                0.000499           0.009507            3       True         45
15         CatBoost_r137_BAG_L2   -2986.390330 -2996.585941  root_mean_squared_error        1.084928       0.265680  299.112916                 0.018500                0.011003          27.308027            2       True         41
16  NeuralNetFastAI_r191_BAG_L1   -2995.017864 -3647.338486  root_mean_squared_error        0.051508       0.029997    2.846124                 0.051508                0.029997           2.846124            1       True         15
17          CatBoost_r13_BAG_L2   -3004.060559 -3326.571425  root_mean_squared_error        1.082928       0.269686  317.114187                 0.016500                0.015010          45.309299            2       True         43
18         LightGBM_r131_BAG_L2   -3025.819645 -2811.983128  root_mean_squared_error        1.256563       0.301181  279.049618                 0.190135                0.046504           7.244730            2       True         34
19              CatBoost_BAG_L2   -3052.648914 -3205.566362  root_mean_squared_error        1.088431       0.267175  320.928179                 0.022003                0.012498          49.123290            2       True         26
20        ExtraTrees_r42_BAG_L2   -3064.574515 -3001.730042  root_mean_squared_error        1.136988       0.306182  272.127127                 0.070560                0.051505           0.322238            2       True         40
21    NeuralNetTorch_r79_BAG_L2   -3065.883152 -3742.537830  root_mean_squared_error        1.136936       0.292176  277.489420                 0.070508                0.037500           5.684531            2       True         33
22         CatBoost_r177_BAG_L2   -3080.215978 -3217.739050  root_mean_squared_error        1.078927       0.266677  296.524378                 0.012499                0.012000          24.719490            2       True         32
23         ExtraTreesMSE_BAG_L2   -3091.316482 -3064.132636  root_mean_squared_error        1.116438       0.308188  272.113060                 0.050010                0.053511           0.308172            2       True         27
24              LightGBM_BAG_L2   -3092.265580 -3055.464850  root_mean_squared_error        1.089932       0.265678  273.173255                 0.023504                0.011002           1.368367            2       True         24
25           CatBoost_r9_BAG_L2   -3131.298998 -3474.998261  root_mean_squared_error        1.101428       0.269182  322.197638                 0.035000                0.014505          50.392749            2       True         36
26  NeuralNetFastAI_r191_BAG_L2   -3164.049361 -3061.031392  root_mean_squared_error        1.118927       0.288683  274.317723                 0.052499                0.034006           2.512835            2       True         35
27           XGBoost_r33_BAG_L2   -3167.930178 -3387.339414  root_mean_squared_error        1.266439       0.278685  276.769606                 0.200011                0.024008           4.964718            2       True         39
28              LightGBM_BAG_L1   -3193.338952 -3977.075535  root_mean_squared_error        0.017000       0.010510    0.730579                 0.017000                0.010510           0.730579            1       True          4
29         LightGBMLarge_BAG_L2   -3214.690043 -3379.416825  root_mean_squared_error        1.181936       0.278676  276.608803                 0.115508                0.023999           4.803914            2       True         31
30       RandomForestMSE_BAG_L1   -3219.229542 -3388.842522  root_mean_squared_error        0.068348       0.055607    0.424011                 0.068348                0.055607           0.424011            1       True          5
31               XGBoost_BAG_L2   -3251.221292 -3450.427324  root_mean_squared_error        1.135935       0.270675  272.854493                 0.069507                0.015999           1.049604            2       True         29
32     RandomForest_r195_BAG_L2   -3269.142358 -3114.404287  root_mean_squared_error        1.108947       0.307175  272.299697                 0.042519                0.052499           0.494809            2       True         44
33            LightGBMXT_BAG_L2   -3278.149933 -3277.663514  root_mean_squared_error        1.101437       0.270673  273.710135                 0.035009                0.015996           1.905247            2       True         23
34       RandomForestMSE_BAG_L2   -3282.008194 -3132.408843  root_mean_squared_error        1.132912       0.304179  272.127325                 0.066484                0.049502           0.322437            2       True         25
35       NeuralNetFastAI_BAG_L2   -3319.241724 -3264.510617  root_mean_squared_error        1.095928       0.282178  274.024728                 0.029500                0.027502           2.219840            2       True         28
36            LightGBMXT_BAG_L1   -3401.803163 -3899.695033  root_mean_squared_error        0.116010       0.011037    0.963560                 0.116010                0.011037           0.963560            1       True          3
37        ExtraTrees_r42_BAG_L1   -3404.710450 -3407.851385  root_mean_squared_error        0.068232       0.049006    0.317089                 0.068232                0.049006           0.317089            1       True         20
38         ExtraTreesMSE_BAG_L1   -3434.253335 -3365.515974  root_mean_squared_error        0.049024       0.049506    0.297758                 0.049024                0.049506           0.297758            1       True          7
39       NeuralNetFastAI_BAG_L1   -3603.839221 -4086.586563  root_mean_squared_error        0.403041       0.026503    2.337707                 0.403041                0.026503           2.337707            1       True          8
40          LightGBM_r96_BAG_L2   -3643.526386 -3565.696942  root_mean_squared_error        1.134434       0.275681  276.737768                 0.068007                0.021004           4.932879            2       True         37
41          LightGBM_r96_BAG_L1   -3648.215147 -4064.037206  root_mean_squared_error        0.062006       0.018010    3.290734                 0.062006                0.018010           3.290734            1       True         17
42    NeuralNetTorch_r22_BAG_L2   -3712.312667 -3666.633702  root_mean_squared_error        1.135930       0.290185  277.915499                 0.069503                0.035508           6.110610            2       True         38
43        KNeighborsDist_BAG_L1   -4769.693921 -5267.790810  root_mean_squared_error        0.016007       0.014521    0.002510                 0.016007                0.014521           0.002510            1       True          2
44        KNeighborsUnif_BAG_L1   -5190.463716 -4814.427859  root_mean_squared_error        0.017515       0.018531    0.003004                 0.017515                0.018531           0.003004            1       True          1
	0	 = Optimal   num_stack_levels (Stacked Overfitting Occurred: True)
	896s	 = DyStack   runtime |	2704s	 = Remaining runtime
Starting main fit with num_stack_levels=0.
	For future fit calls on this dataset, you can skip DyStack to save time: `predictor.fit(..., dynamic_stacking=False, num_stack_levels=0)`
Beginning AutoGluon training ... Time limit = 2704s
AutoGluon will save models to "f:\car-project\AutogluonModels\ag-20250725_012410"
Train Data Rows:    594
Train Data Columns: 17
Label Column:       price
Problem Type:       regression
Preprocessing data ...
Using Feature Generators to preprocess the data ...
Fitting AutoMLPipelineFeatureGenerator...
	Available Memory:                    13396.42 MB
	Train Data (Original)  Memory Usage: 0.16 MB (0.0% of available memory)
	Inferring data type of each feature based on column values. Set feature_metadata_in to manually specify special dtypes of the features.
	Stage 1 Generators:
		Fitting AsTypeFeatureGenerator...
			Note: Converting 1 features to boolean dtype as they only contain 2 unique values.
	Stage 2 Generators:
		Fitting FillNaFeatureGenerator...
	Stage 3 Generators:
		Fitting IdentityFeatureGenerator...
		Fitting CategoryFeatureGenerator...
			Fitting CategoryMemoryMinimizeFeatureGenerator...
	Stage 4 Generators:
		Fitting DropUniqueFeatureGenerator...
	Stage 5 Generators:
		Fitting DropDuplicatesFeatureGenerator...
	Types of features in original data (raw dtype, special dtypes):
		('bool', [])   :  1 | ['title_status']
		('float', [])  : 12 | ['suv_prob', 'vert_prob', 'sedan_prob', 'coupe_prob', 'hatchback_prob', ...]
		('int', [])    :  1 | ['year']
		('object', []) :  3 | ['make', 'model_name', 'transmission']
	Types of features in processed data (raw dtype, special dtypes):
		('category', [])  :  3 | ['make', 'model_name', 'transmission']
		('float', [])     : 12 | ['suv_prob', 'vert_prob', 'sedan_prob', 'coupe_prob', 'hatchback_prob', ...]

In [ ]:
# predictor = TabularPredictor.load("f:\car-project\AutogluonModels\ag-20250725_012410")

In [100]:
predictor2.feature_importance(ag_df)

Computing feature importance via permutation shuffling for 17 features using 594 rows with 5 shuffle sets...
	39.16s	= Expected runtime (7.83s per shuffle set)
	14.27s	= Actual runtime (Completed 5 of 5 shuffle sets)

,importance,stddev,p_value,n,p99_high,p99_low
year,2512.826023,72.627344,8.364667e-08,5,2662.366728,2363.285318
mileage,1836.903053,102.770076,1.170827e-06,5,2048.508060,1625.298046
model_name,787.953122,35.245100,4.790899e-07,5,860.523271,715.382974
coupe_prob,715.340360,51.966102,3.318648e-06,5,822.339282,608.341438
make,613.909946,36.107057,1.429323e-06,5,688.254875,539.565017
sedan_prob,326.835511,53.775724,8.485818e-05,5,437.560469,216.110553
suv_prob,223.742002,51.162442,3.064141e-04,5,329.086177,118.397827
hatchback_prob,173.089510,35.461584,2.000821e-04,5,246.105402,100.073618
excellent_cond_prob,132.846960,14.598751,1.722174e-05,5,162.905990,102.787930
bumper_damage_prob,129.476620,15.519332,2.430156e-05,5,161.431139,97.522101
door_damage_prob,129.397866,17.187218,3.648780e-05,5,164.786587,94.009146
vert_prob,115.569223,12.902659,1.833774e-05,5,142.135976,89.002470
average_cond_prob,71.484252,10.290282,5.013533e-05,5,92.672085,50.296419
transmission,57.598903,4.430662,4.168504e-06,5,66.721698,48.476109
window_damage_prob,55.907845,11.673279,2.153922e-04,5,79.943288,31.872402
hood_damage_prob,38.938693,6.858745,1.108865e-04,5,53.060944,24.816443
title_status,28.255046,10.052141,1.636356e-03,5,48.952544,7.557549

In [ ]:
predictor2.evaluate(ag_df) # train performance

{'root_mean_squared_error': np.float64(-1551.2164267578162),
 'mean_squared_error': -2406272.402643287,
 'mean_absolute_error': -943.9442056469644,
 'r2': 0.9309330058866514,
 'pearsonr': 0.9694210236072863,
 'median_absolute_error': np.float64(-530.40625)}